
default: &default
<<<<<<< HEAD
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: authentication_developement
=======
 adapter: postgresql
 encoding: unicode
 pool: 5


development:
 <<: *default
 database: jpjennings_development
 
>>>>>>> e9f90235c46fd06fcbeb9331c3f1464488660c1d

test:
<<<<<<< HEAD
  <<: *default
  database: authentication_test

production:
  <<: *default
  database: authentication_production
  password: <%= ENV['AUTHENTICATION_DATABASE_PASSWORD'] %>
=======
 <<: *default
 database: jpjennings_test


production:
 <<: *default
 database: jpjennings_production
 username: jpjennings
 password: <%= ENV['JPJENNINGS_DATABASE_PASSWORD'] %>
>>>>>>> e9f90235c46fd06fcbeb9331c3f1464488660c1d
