
default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5


development:
 <<: *default
 database: jpjennings_development
 

test:
 <<: *default
 database: jpjennings_test


production:
 <<: *default
 database: jpjennings_production
 username: jpjennings
 password: <%= ENV['JPJENNINGS_DATABASE_PASSWORD'] %>